In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50])

In [3]:
print(arr)

[10 20 30 40 50]


In [4]:
arr.shape

(5,)

In [5]:
len(arr)

5

In [6]:
arr_2d = np.array([
    [10,20,30,40,50],
    [100,200,300,400,500]
])

In [7]:
print(arr_2d)

[[ 10  20  30  40  50]
 [100 200 300 400 500]]


In [8]:
arr_2d.shape

(2, 5)

In [9]:
arr_2d.ndim

2

In [10]:
type(arr_2d)

numpy.ndarray

In [11]:
arr_2d.dtype

dtype('int64')

In [12]:
arr_3d = np.array([
    [
        [1,2],
        [3,4],
        [5,6]
    ],
    [
        [11,12],
        [13,14],
        [15,16]
    ]
])

In [13]:
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[11, 12],
        [13, 14],
        [15, 16]]])

In [14]:
arr_3d.dtype

dtype('int64')

In [15]:
type(arr_3d)

numpy.ndarray

In [16]:
arr_3d.shape

(2, 3, 2)

In [17]:
np.zeros(shape=(2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
np.full(shape=(3,5), fill_value='cat')

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

In [19]:
np.arange(1,5,1)

array([1, 2, 3, 4])

In [20]:
small_zeros = np.zeros(shape=(3,4))

In [21]:
len(small_zeros)

3

In [22]:
for i in range(len(small_zeros)):
    small_zeros[i,] = np.arange(1,5,1)
    
print(small_zeros)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [23]:
np.random.randint(1,9, size=(3,5))

array([[4, 3, 4, 1, 8],
       [8, 4, 3, 7, 4],
       [2, 8, 7, 8, 1]])

In [24]:
foo = np.array([10,20,30,40,50])

In [25]:
foo[1]

20

In [26]:
foo[[0,1]]

array([10, 20])

In [27]:
foo[[0,1,0,1]]

array([10, 20, 10, 20])

In [28]:
foo[np.zeros(shape=3)]

IndexError: arrays used as indices must be of integer (or boolean) type

In [29]:
np.zeros(shape=3)

array([0., 0., 0.])

In [30]:
np.zeros(shape=3, dtype = int)

array([0, 0, 0])

In [31]:
foo[np.zeros(shape=3, dtype = 'int64')]

array([10, 10, 10])

In [32]:
foo[:2]

array([10, 20])

In [33]:
foo[2:]

array([30, 40, 50])

In [34]:
foo[::2]

array([10, 30, 50])

In [35]:
foo[[0,1,4]] = [100,200,500]

In [36]:
foo

array([100, 200,  30,  40, 500])

In [37]:
bar = np.array([
    [5,10,15,20],
    [25,30,35,40],
    [45,50,55,60]
])

In [38]:
bar 

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [39]:
bar[:,2]

array([15, 35, 55])

In [40]:
bar[1:3, [-2,-1]]

array([[35, 40],
       [55, 60]])

In [41]:
bar[0,0] = -1
print(bar)

[[-1 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


In [42]:
bar[1] = bar[2]

In [43]:
print(bar)

[[-1 10 15 20]
 [45 50 55 60]
 [45 50 55 60]]


In [44]:
bar[[0,1,2],[0,1,2]]

array([-1, 50, 55])

In [45]:
bar[[0,1,2],[0,1,2]] = [0,0,0]

In [46]:
print(bar)

[[ 0 10 15 20]
 [45  0 55 60]
 [45 50  0 60]]


In [47]:
zoo = np.zeros(shape=(2,3,2))
print(zoo)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [48]:
zoo[0,:,1] = 5

In [72]:
print(zoo)

[[[0. 5.]
  [0. 5.]
  [0. 5.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [49]:
foo = np.array([[4,3],[1,0]])
bar = np.array([[1,2],[3,4]])

In [50]:
print(foo)
print(bar)

[[4 3]
 [1 0]]
[[1 2]
 [3 4]]


In [51]:
foo + bar

array([[5, 5],
       [4, 4]])

In [52]:
foo - bar

array([[ 3,  1],
       [-2, -4]])

In [53]:
foo * bar

array([[4, 6],
       [3, 0]])

In [54]:
foo / bar

array([[4.        , 1.5       ],
       [0.33333333, 0.        ]])

In [55]:
foo @ bar

array([[13, 20],
       [ 1,  2]])

In [56]:
foo + np.full(shape=(2,2), fill_value=5)

array([[9, 8],
       [6, 5]])

In [57]:
foo + 5

array([[9, 8],
       [6, 5]])

In [69]:
daily_wts = 185 - np.arange(5*7)/5
print(daily_wts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


In [70]:
daily_wts[5::7]

array([184. , 182.6, 181.2, 179.8, 178.4])

In [71]:
daily_wts[6::7]

array([183.8, 182.4, 181. , 179.6, 178.2])

In [72]:
(daily_wts[5::7] + daily_wts[6::7])/2

array([183.9, 182.5, 181.1, 179.7, 178.3])

In [74]:
np.random.seed(42)
gold = np.random.randint(low=0, high=10, size=(7,7))
print(gold)

[[6 3 7 4 6 9 2]
 [6 7 4 3 7 7 2]
 [5 4 1 7 5 1 4]
 [0 9 5 8 0 9 2]
 [6 3 8 2 4 2 6]
 [4 8 6 1 3 8 1]
 [9 8 9 4 1 3 6]]


In [75]:
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

In [76]:
print(locs)

[[0 4]
 [2 2]
 [2 3]
 [5 1]
 [6 3]]


In [77]:
gold_total = 0
for el in locs:
    gold_total += gold[el[0]][el[1]]
    
print(gold_total)

26


In [82]:
# alternative solution

gold[locs[:,0],locs[:,1]].sum()

26

In [86]:
np.linspace([17,28],[28,36], num = 3, axis = 1)

array([[17. , 22.5, 28. ],
       [28. , 32. , 36. ]])

In [88]:
np.abs(np.linspace([17,28],[28,36], num = 3, axis = 1) - 30)

array([[13. ,  7.5,  2. ],
       [ 2. ,  2. ,  6. ]])

In [90]:
np.abs(np.linspace([17,28],[28,36], num = 3, axis = 1) - 30)[[0,1],[2,0]]

array([2., 2.])

Broadcasting

In [105]:
A = np.array([1,2,3,4])
B = np.array([5,0,3])

print(A, B)

[1 2 3 4] [5 0 3]


In [106]:
A[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [107]:
B[:, np.newaxis]

array([[5],
       [0],
       [3]])

In [108]:
A.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [109]:
np.reshape(A, newshape=(2,2))

array([[1, 2],
       [3, 4]])

In [110]:
A.reshape(2,2, order='C')

array([[1, 2],
       [3, 4]])

In [111]:
A.reshape(2,2, order='F')

array([[1, 3],
       [2, 4]])

In [112]:
A.reshape(2,-1)

array([[1, 2],
       [3, 4]])

In [113]:
A.shape = (2,-1)

In [114]:
A

array([[1, 2],
       [3, 4]])

In [115]:
A = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8],
])

In [116]:
A.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [117]:
np.transpose(A)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [118]:
foo = np.random.randint(1,9, size=(3,3))

In [119]:
foo

array([[4, 5, 8],
       [7, 3, 6],
       [1, 4, 2]])

In [120]:
foo == 3

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [121]:
mask = foo == 3

In [123]:
foo[mask] = 0
print(foo)

[[4 5 8]
 [7 0 6]
 [1 4 2]]


In [127]:
row_1_and_3 = np.array([True,False,True])
col_2_and_3 = np.array([False,True,True])

In [130]:
foo[row_1_and_3] # like foo[[0,2]]

array([[4, 5, 8],
       [1, 4, 2]])

In [131]:
foo[:, col_2_and_3] # like foo[:,[1,2]]

array([[5, 8],
       [0, 6],
       [4, 2]])

In [132]:
foo[row_1_and_3, col_2_and_3] # like foo[[0,2],[1,2]] selects elements (0,1) and (2,2)

array([5, 2])

In [133]:
names=np.array(['Denis', 'Charlize', 'Mark', 'Frank', 'Jason'])
ages = np.array([34,46,44,56,36])
genders= np.array(['male', 'female', 'male', 'male', 'male'])

In [134]:
ages >= 40

array([False,  True,  True,  True, False])

In [135]:
names[ages >= 40]

array(['Charlize', 'Mark', 'Frank'], dtype='<U8')

In [137]:
names[(genders == 'male') & (ages > 40)]

array(['Mark', 'Frank'], dtype='<U8')

In [139]:
np.array([np.inf, np.NINF])

array([ inf, -inf])

In [140]:
np.array([-1,1])/0

/home/ddyakov/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([-inf,  inf])

In [141]:
np.inf + 2

inf

In [142]:
np.inf + np.inf

inf

In [143]:
np.inf - np.inf

nan

In [144]:
np.inf == np.inf

True

In [145]:
np.NINF == np.NINF

True